### PR TITLE
Sets NODE_ENV correctly

### PR DESCRIPTION
**Pull request by matthewrbrooks**
# Details
Sets NODE_ENV correctly for various build options

### CODE REVIEW

**Review by craigjohnwright — APPROVED** [review]

**Review by andyj-bbc — CHANGES_REQUESTED** [review]
I don’t think we should be giving the responsibility of controlling the NODE_ENV to our code, that is too closely coupled imo. The only thing we should concern ourselves with is to publish production code which we can control by setting that env variables when we run the publishing scripts or get jenkins to do so.
 Adds more dependencies which we can avoid, and this package is deprecated and in maintenance mode.

**Comment by craigjohnwright** [comment]
I don't mind this as a solution at all. It's a fairly endemic pattern. I would prefer to have it set in a `.env` file and honoured in `package.json`.

**Comment by andyj-bbc** [comment]
> I don't mind this as a solution at all. It's a fairly endemic pattern. I would prefer to have it set in a `.env` file and honoured in `package.json`.

https://github.com/motdotla/dotenv this is a better solution then, i've used it here https://github.com/bbc/nbe-cloudfit-js-sdk/ in the `yarn demo` command, but i think this `require('dotenv').config()` in webpack config would work too, then we could separate dev and production environments

**Comment by matthewrbrooks** [comment]
> > I don't mind this as a solution at all. It's a fairly endemic pattern. I would prefer to have it set in a `.env` file and honoured in `package.json`.
> 
> https://github.com/motdotla/dotenv this is a better solution then, i've used it here https://github.com/bbc/nbe-cloudfit-js-sdk/ in the `yarn demo` command, but i think this `require('dotenv').config()` in webpack config would work too, then we could separate dev and production environments

That still requires anyone running package generation themselves to remember to change their env. Which is why I'd prefer it against the package.json scripts. Can't get it wrong.

**Comment by craigjohnwright** [comment]
Switching to using native Webpack _env_ looks good to me 👍

**Review by craigjohnwright — APPROVED** [review]

**Pull request merged**
